import os

DEFAULT_DB_PORT = 3306  # MySQL
DEFAULT_MQ_PORT = 5672  # rabbit mq
DEFAULT_SERVER_PORT = 6363
DEFAULT_CONFIG = {
    "portno": DEFAULT_SERVER_PORT,
    "mq_port": DEFAULT_MQ_PORT,
    "db_port": DEFAULT_DB_PORT
}

DB_DIR = os.path.join(
    os.path.expanduser("~"),
    ".wifi_map",
)

DB_FILE = os.path.join(
    DB_DIR,
    "wifi_map.db"
)

FRAME_TYPE_MGMT = 0x0
FRAME_TYPE_CTRL = 0x1
FRAME_TYPE_DATA = 0x2

FRAME_SUBTYPE_ASSOC_REQ = 0x0
FRAME_SUBTYPE_ASSOC_RES = 0x1
FRAME_SUBTYPE_REASSOC_REQ = 0x2
FRAME_SUBTYPE_REASSOC_RES = 0x3
FRAME_SUBTYPE_PROBE_REQ = 0x4
FRAME_SUBTYPE_PROBE_RES = 0x5
FRAME_SUBTYPE_BEACON = 0x8
FRAME_SUBTYPE_DISAS = 0xA
FRAME_SUBTYPE_AUTH = 0xB
FRAME_SUBTYPE_DEUATH = 0xC

FC_FLAG_TO_DS = 0x1
FC_FLAG_FROM_DS = 0x2

ADDRESS_RCV = "reciever"
ADDRESS_TRNSMT = "transmitter"
ADDRESS_SRC = "source"
ADDRESS_DST = "destination"
ADDRESS_BSSID = "bssid"

MAC_BROADCAST = "ff:ff:ff:ff:ff:ff"
MAC_NONE = "00:00:00:00:00:00"
